name: CI/CD Pipeline for Wordpress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --no-interaction

      - name: Copy uploads.tar.gz to container
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          local: ./uploads.tar.gz
          remote: /var/www/html/uploads.tar.gz

      - name: Deploy to production
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/
            sudo rm -rf *
            sudo tar -xzvf uploads.tar.gz
            sudo rm -f uploads.tar.gz
            sudo wp db flush
            sudo wp rewrite flush
            sudo wp search-replace "http://legacy-url.com" "https://s3-bucket-url.com" --skip-columns=guid
